# Generated by Django 4.1 on 2022-12-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(max_length=200)),
                ('objet_social', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='dashboard/assets/images/user/user.png', null=True, upload_to='files/ense_pic')),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etude', models.CharField(blank=True, choices=[('Licence', 'Licence'), ('DEA', 'DEA'), ('Maîtrise/Master', 'Maîtrise/Master'), ('Doctorat/Phd', 'Doctorat/Phd')], max_length=50, null=True)),
                ('grade', models.CharField(blank=True, choices=[('Assisstant', 'Assisstant'), ('Maître assisstant/Maître de recherche', 'Maître assisstant/Maître de recherche'), ('Maître de conférences', 'Maître de conférences'), ('Professeur titulaire/Directeur de recherche', 'Professeur titulaire/Directeur de recherche')], max_length=50, null=True)),
                ('faculte', models.CharField(blank=True, max_length=50, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('pays_affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_graduation', models.DateField(blank=True, null=True)),
                ('tel', models.PositiveIntegerField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('fbook_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='files/profic_pic/t_user.png', null=True, upload_to='files/profic_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
