# Generated by Django 3.2.4 on 2022-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220331_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='niveau_etude',
            field=models.CharField(choices=[('License', 'License'), ('Maîtrise', 'Maîtrise'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('DEA', 'DEA'), ('Professorat', 'Professorat')], max_length=50),
        ),
    ]
