# Generated by Django 3.2.4 on 2022-04-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='domaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categorie'),
            preserve_default=False,
        ),
    ]
