# Generated by Django 3.2.4 on 2022-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_comment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(),
        ),
    ]
