# Generated by Django 3.2.4 on 2022-04-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('Thèse', 'Thèse'), ('Mémoire', 'Mémoire'), ('Rapport de stage', 'Rapport de stage'), ('Document de synthèse', 'Document de synthèse'), ('Article', 'Article'), ('Livre', 'Livre')], max_length=100, null=True),
        ),
    ]
